#spring:
#  cloud:
#    stream:
#      bindings:
#        log_input:
#          destination: kite.log.messages
#          binder: local_rabbit
#          group: logConsumer-group1
#        log_output:
#          destination: kite.log.messages
#          binder: local_rabbit
#        log_format_input:
#          destination: kite.log.format.messages
#          binder: local_rabbit
#          group: logFormat-group1
#        log_format_output:
#          destination: kite.log.format.messages
#          binder: local_rabbit
#      binders:
#        local_rabbit:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: localhost
#                port: 5672
#                username: guest
#                password: guest

app:
  id: rabbit-mq

apollo:
  bootstrap:
    enabled: false

server:
  port: 8210