spring:
  application:
    name: demo-producer-application
  cloud:
    # Spring Cloud Stream 配置项，对应 BindingServiceProperties 类
    stream:
      # Binder 配置项，对应 BinderProperties Map
      #      binders:
      # Binding 配置项，对应 BindingProperties Map
      bindings:
        output:
          destination: DEMO-TOPIC-02 # 目的地。这里使用 Kafka Topic
          content-type: application/json # 内容格式。这里使用 JSON
        input:
          destination: DEMO-TOPIC-02 # 目的地。这里使用 Kafka Topic
          content-type: application/json # 内容格式。这里使用 JSON
          group: demo01-consumer-group # 消费者分组
          max-attempts: 2 # 重试次数，默认为 3 次。
          back-off-initial-interval: 1000 # 重试间隔的初始值，单位毫秒，默认为 1000
          back-off-multiplier: 2.0 # 重试间隔的递乘系数，默认为 2.0
          back-off-max-interval: 6000 # 重试间隔的最大值，单位毫秒，默认为 10000
      # Spring Cloud Stream Kafka 配置项
      kafka:
        # Kafka Binder 配置项，对应 KafkaBinderConfigurationProperties 类
        binder:
          brokers: 127.0.0.1:9092 # 指定 Kafka Broker 地址，可以设置多个，以逗号分隔
        # Kafka 自定义 Binding 配置项，对应 KafkaBindingProperties Map
        bindings:
          output:
            # Kafka Producer 配置项，对应 KafkaProducerProperties 类
            producer:
              sync: true # 是否同步发送消息，默认为 false 异步。
          input:
            consumer:
              enable-dlq: true #是否开启死信队列，默认为 false 关闭
              dlq-name:  # 死信队列名，默认为 `errors.{topicName}.{consumerGroup}`

management:
  endpoints:
    web:
      exposure:
        include: '*' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。
  endpoint:
    # Health 端点配置项，对应 HealthProperties 配置类
    health:
      enabled: true # 是否开启。默认为 true 开启。
      show-details: ALWAYS # 何时显示完整的健康信息。默认为 NEVER 都不展示。可选 WHEN_AUTHORIZED 当经过授权的用户；可选 ALWAYS 总是展示。
